env = XKB_DEFAULT_RULES:evdev
env = XKB_DEFAULT_MODEL:pc105
env = XKB_DEFAULT_LAYOUT:us_custom
env = XKB_DEFAULT_VARIANT:custom
env = XKB_CONFIG_ROOT:/home/admin/configs/sec_test.xkb

exec-once = hyprpm reload -n
exec-once = /usr/bin/pypr
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = systemctl --user start plasma-polkit-agent
exec-once = /home/admin/.conda/envs/server/bin/python -m server start test
exec-once = eww open simple_bar 

exec-once = hyprpaper 
