env = XKB_DEFAULT_RULES:evdev
env = XKB_DEFAULT_MODEL:pc105
env = XKB_DEFAULT_LAYOUT:us_custom
env = XKB_DEFAULT_VARIANT:custom
env = XKB_CONFIG_ROOT:/home/admin/configs/sec_test.xkb
env = XCURSOR_THEME,"default"
env = XCURSOR_SIZE,20
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

exec-once = hyprpm reload -n
exec-once = /usr/bin/pypr

exec-once = systemctl --user start hyprpolkitagent

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = /home/admin/.conda/envs/server/bin/python -m server start test
exec-once = eww open simple_bar 

exec-once=wpaperd -d
