env = XKB_DEFAULT_RULES:evdev
env = XKB_DEFAULT_MODEL:pc105
env = XKB_DEFAULT_LAYOUT:us_custom
env = XKB_DEFAULT_VARIANT:custom
env = XKB_CONFIG_ROOT:/home/admin/configs/sec_test.xkb


env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1 

env = HYPRCURSOR_THEME,"Future-Cyan-Hyprcursor_Theme"

exec-once = hyprpm reload -n
exec-once = /usr/bin/pypr

exec-once = systemctl --user start hyprpolkitagent

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = /home/admin/.conda/envs/server/bin/python -m server start test
exec-once = eww open simple_bar 

exec-once = while true; do mpvpaper "*" -o "input-ipc-server=/tmp/mpv-socket" ~/wallpapers/FirstExponential.mp4 && mpvpaper "*" -o "input-ipc-server=/tmp/mpv-socket" ~/wallpapers/ZetaSpiralAnimation.mp4 && mpvpaper "*" -o "input-ipc-server=/tmp/mpv-socket" ~/wallpapers/Background.mp4 &&  mpvpaper "*" -o "input-ipc-server=/tmp/mpv-socket" ~/wallpapers/WideLong.mp4 && mpvpaper "*" -o "input-ipc-server=/tmp/mpv-socket" ~/wallpapers/RandomGraphTraversal.mp4; done
# exec-once=wpaperd -d
