$inactive = rgb(d82799)
$mid_inactive = rgb(1f2538)
$end_inactive = rgb(1f2538)
$active = rgb(24a931)
$mid_active = rgb(911ae5)
$before_end_active = rgb(1f2538)
$end_active = rgb(1f2538)
$highlight = rgb(911ae5)
$background = rgb(1f2538)
$shadow = rgb(004C4E)
$shadow_inactive = rgb(420C14)
$shadow_inactive = rgb(420C14)
