$inactive = rgb(E93636)
$mid_inactive = rgb(AB9B09)
$end_inactive = rgb(1E282D)
$active = rgb(45E931)
$mid_active = rgb(01E3FF)
$before_end_active = rgb(37872D)
$end_active = rgb(1E282D)
$highlight         = rgb(AF31E9)


