$inactive = rgb(951F31)
$mid_inactive = rgb(AB9B09)
$end_inactive = rgb(1E282D)
$active = rgb(4BFF34)
$mid_active = rgb(00B6CD)
$before_end_active = rgb(010101)
$end_active = rgb(1E282D)
$highlight = rgb(AF31E9)
$background = rgb(1E282D)
$shadow = rgb(005B67)
$shadow_inactive = rgb(2C080E)


