plugin:hyprfocus {
    enabled = false
    animate_floating = false
    animate_workspacechange = false
    focus_animation = shrink
    bezier = realsmooth, 0.28,0.29,.69,1.08
    flash {
        flash_opacity = 0.9
        in_bezier = realsmooth
        in_speed = 1
        out_bezier = realsmooth
        out_speed = 1
    }
    shrink {
        shrink_percentage = 0.9
        in_bezier =  realsmooth
        in_speed = 1
        out_bezier = realsmooth
        out_speed = 1
    }
}

plugin:dynamic-cursors {
    enabled = true
    mode = tilt 
    threshold = 3
#   rotate {
#       length = 20
#       offset = 0.0
#   }

    tilt {
        limit = 3000
        function = negative_quadratic
    }

#   stretch {
#       limit = 3000
#       function = quadratic
#   }

    shake {
        enabled = true
        nearest = true 
        threshold = 5.0
        base = 4.0
        speed = 4.0
        influence = 0.0
        limit = 0.0
        timeout = 2000
        effects = true 
        ipc = true 
    }
}
