
env = ELECTRON_OZONE_PLAT_PLATFORM_HINT,auto
env = NVD_BACKEND,direct
env = __GL_GSYNC_ALLOWED,1

env = CRYPTOGRAPHY_OPENSSL_NO_LEGACY,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env= HYPRLAND_TRACE,1
env= AQ_TRACE,1

env= PATH,/opt/cuda/bin:$PATH
env= LD_LIBRARY_PATH,/opt/cuda/lib64:$LD_LIBRARY_PATH
env= LD_LIBRARY_PATH,$LD_LIBRARY_PATH:/opt/cuda/extras/CUPTI/lib64
env= TF_FORCE_GPU_ALLOW_GROWTH,true
env= PYTHONDONTWRITEBYTECODE,1

