windowrulev2 = tag +see, title:(SeeThrough)

windowrulev2 = tag +code, class:neovide
windowrulev2 = noblur, class:kitty
windowrulev2 = opacity 0.98 0.7 1, class:kitty
windowrulev2 = tile, class:kitty

windowrulev2 = tag +auto, title:(Console)
windowrulev2 = tag +auto, class:(CarlaUE4-Linux-Shipping)
windowrulev2 = tag +auto, title:(CarlaUE4)
windowrulev2 = tag +auto, class:(imv)

windowrulev2 = tag +read, class:(org.pwmt.zathura)

windowrulev2 = tile, class:(org.kde.okular)
windowrulev2 = tile, tag:code

windowrulev2 = opacity 0.98 0.4 1, tag:code

windowrulev2 = opacity 1,        tag:auto
windowrulev2 = monitor HDMI-A-1, tag:auto

windowrulev2 = suppressevent activatefocus activate,   tag:auto

windowrulev2 = noinitialfocus,   tag:auto

windowrulev2 = noinitialfocus,   tag:read
windowrulev2 = opacity 1,        tag:read

windowrulev2 = noblur,           tag:see
windowrulev2 = opacity 0.8,      tag:see

windowrulev2 = tile,             class:(CarlaUE4-Linux-Shipping)
windowrule   = opacity 1 0.95 0.9,^(google-chrome)$

#windowrulev2 = animation borderangle 1 300 myBezier once, tag:see

#windowrule   = immediate,^(google-chrome)$

# DLR Simulation

# windowrulev2 = workspace name:main,        class:(firefox)
#


# windowrule   = opacity 1 0.4 0.9, ^(neovide)$
# windowrule   = dimaround,         ^(neovide)$

# windowrule   = noblur,            ^(kitty)$
# windowrule   = opacity 1 0.6 0.9, ^(kitty)$
# windowrule   = focusonactivate,   ^(kitty)$


