
# DLR Simulation
windowrule = monitor HDMI-A-1,  ^(CarlaUE4-Linux-Shipping)$
windowrule = tile,              ^(CarlaUE4-Linux-Shipping)$
windowrule = noinitialfocus,    ^(CarlaUE4-Linux-Shipping)$

windowrulev2 = opacity 1, title:(Console)
windowrulev2 = workspace name:vert, title:(Console)

windowrulev2 = noblur,          title:(SeeThrow)

windowrule = unset,                  ^(neovide)$
# windowrule = workspace special, ^(neovide)$

windowrule   = opacity 1 0.4 0.9, ^(neovide)$
windowrule   = noblur,            ^(kitty)$
windowrule   = opacity 1 0.7 0.9, ^(kitty)$

windowrule   = focusonactivate,       ^(kitty)$

windowrule   = opacity 1 override 0.9 override,^(Google-chrome)$

bind = SUPERSHIFT,       c, exec, kitty --title "Console" -o allow_remote_control=yes --listen-on unix:/tmp/mykitty > /dev/null 2>&1
bind = SUPER SHIFT,      S, exec, ~/configs/hyprland/skripts/screenshots.sh

bind = SUPER, E, exec, thunar
bind = SUPER, R, exec, tofi-drun


