windowrulev2 = tag +see, title:(SeeThrough)
windowrulev2 = tag +code, class:neovide


windowrulev2 = plugin:scroller:columnwidth onefourth,        class:(chrome)

#282828
#0E0E0E
chromakey_background= 30, 30, 30

windowrulev2 = plugin:chromakey, class:^(kitty)$
windowrulev2 = plugin:chromakey, class:^(google-chrome)$
# windowrulev2 = plugin:chromakey, class:^(neovide)$


windowrulev2 = tile, class:pavucontrol-qt

windowrulev2 = animation fade,                     class:(neovide)
windowrulev2 = plugin:scroller:columnwidth one,    class:(neovide)
windowrulev2 = noblur,    title:(SeeThrough)


windowrulev2 = plugin:scroller:columnwidth one, title:(startup) # used for the kitty terminal opening after boot
windowrulev2 = plugin:scroller:columnwidth onethird, title:(kitty)

windowrulev2 = noblur,              class:kitty
windowrulev2 = opacity    1 0.9 1,  class:kitty
windowrulev2 = tile,                class:kitty
windowrulev2 = renderunfocused,     class:kitty

windowrulev2 = tag +auto, title:(Console)

windowrulev2 = tag auto, class:(CarlaUE4-Linux-Shipping)
windowrulev2 = tag auto, title:(CarlaUE4)

windowrulev2 = tag +read,  class:(org.pwmt.zathura)

windowrulev2 = tag +plot, class:(Matplotlib)
windowrulev2 = tag +plot, class:(vimiv)
windowrulev2 = tag +plot, class:(mpv)
windowrulev2 = tag +plot, class:(imv)

windowrulev2 = tile, class:(org.kde.okular)

windowrulev2 = tile,                tag:code
windowrulev2 = opacity 0.98 0.7 1,  tag:code

windowrulev2 = opacity 1,        tag:no_darken

windowrulev2 = tile, class:(CarlaUE4-Linux-Shipping)
windowrulev2 = monitor HDMI-A-1,    class:(CarlaUE4-Linux-Shipping)
windowrulev2 = renderunfocused,     class:(CarlaUE4-Linux-Shipping)
windowrulev2 = idleinhibit always,  class:(CarlaUE4-Linux-Shipping)

windowrulev2 = tag +internet, class:chrome

windowrulev2 = opacity 1,                            tag:auto
windowrulev2 = monitor HDMI-A-1,                     tag:auto
windowrulev2 = suppressevent activatefocus,          tag:auto
windowrulev2 = focusonactivate off,                  tag:auto
windowrulev2 = noinitialfocus,                       tag:auto

# windowrulev2 = plugin:scroller:group internet,      tag:internet
windowrulev2 = plugin:scroller:mode column,         tag:internet
windowrulev2 = plugin:scroller:fitsize active,      tag:internet

windowrulev2 = monitor DP-1,                        tag:internet
windowrulev2 = opacity 0.90 0.80 0.9,               tag:internet
windowrulev2 = noblur                               tag:internet

windowrulev2 = plugin:scroller:group python_plots,  tag:plot
windowrulev2 = plugin:scroller:mode column,         tag:plot
windowrulev2 = monitor HDMI-A-1,                    tag:plot

windowrulev2 = opacity 1,        tag:read
windowrulev2 = noblur,           tag:see
windowrulev2 = opacity 0.8,      tag:see
