plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 1
        enable_notifications = 0
    }
}

workspace=name:1,monitor:DP-1
workspace=special:1,gapsout:25,gapsin:10,monitor:DP-1

workspace=name:2,monitor:HDMI-A-1
workspace=special:2,monitor:HDMI-A-1

bind = SUPER, 1, split-workspace, 1
bind = SUPER, 2, split-workspace, 2
bind = SUPER, 3, split-workspace, 3
bind = SUPER, 4, split-workspace, 4
bind = SUPER, 5, split-workspace, 5

bind = SUPERSHIFT, 1, split-movetoworkspace, 1
bind = SUPERSHIFT, 2, split-movetoworkspace, 2
bind = SUPERSHIFT, 3, split-movetoworkspace, 3
bind = SUPERSHIFT, 4, split-movetoworkspace, 4
bind = SUPERSHIFT, 5, split-movetoworkspace, 5


bind = SUPER,       u, split-movetoworkspace, special:1
bind = SUPER,   SPACE, togglespecialworkspace, 1
