


workspace= special, gapsout:25,gapsin:10,monitor:HDMI-A-1

workspace= 1, gapsout:25,gapsin:10,monitor:HDMI-A-1
workspace= 2, gapsout:25,gapsin:10,monitor:HDMI-A-1
workspace= 3, gapsout:25,gapsin:10,monitor:HDMI-A-1
            
workspace= 4, gapsout:10,gapsin:3,monitor:DP-1
workspace= 5, gapsout:10,gapsin:3,monitor:DP-1
workspace= 6, gapsout:10,gapsin:3,monitor:DP-1

workspace=name:1,     monitor:HDMI-A-1
workspace=name:2,     monitor:HDMI-A-1
workspace=name:3,     monitor:HDMI-A-1

workspace=name:4,     monitor:DP-1
workspace=name:5,     monitor:DP-1
workspace=name:6,     monitor:DP-1

#workspace=name:1,     monitor:DP-1
#workspace=name:2,     monitor:DP-1
#workspace=name:3,     monitor:HDMI-A-1
#workspace=name:4,     monitor:HDMI-A-1

exec-once = hyprctl dispatch moveworkspacetomonitor 3 HDMI-A-1
exec-once = hyprctl dispatch moveworkspacetomonitor 4 DP-1

exec-once = kitty --title 'startup' --hold sh -c 'neofetch'
