#plugin {
#   split-monitor-workspaces {
#       count = 2
#       keep_focused = 1
#       enable_notifications = 0
#   }
#}

workspace = special:exposed,gapsout:60,gapsin:30,bordersize:5,border:true,shadow:false
workspace=special:s1, gapsout:25,gapsin:10,monitor:HDMI-A-1
workspace=special:s2, gapsout:25,gapsin:10,monitor:DP-1

workspace=name:1,     monitor:HDMI-A-1
workspace=name:2,     monitor:HDMI-A-1
workspace=name:3,     monitor:HDMI-A-1
workspace=name:4,     monitor:DP-1
workspace=name:5,     monitor:DP-1
workspace=name:6,     monitor:DP-1

workspace=special:-1,     monitor:HDMI-A-1
workspace=special:-2,     monitor:HDMI-A-1
workspace=special:-3,     monitor:HDMI-A-1
workspace=special:-4,     monitor:DP-1
workspace=special:-5,     monitor:DP-1
workspace=special:-6,     monitor:DP-1

#workspace=name:1,     monitor:DP-1
#workspace=name:2,     monitor:DP-1
#workspace=name:3,     monitor:HDMI-A-1
#workspace=name:4,     monitor:HDMI-A-1

exec-once = hyprctl dispatch moveworkspacetomonitor 3 HDMI-A-1
exec-once = hyprctl dispatch moveworkspacetomonitor 4 DP-1

exec-once = hyprctl dispatch moveworkspacetomonitor -3 HDMI-A-1
exec-once = hyprctl dispatch moveworkspacetomonitor -4 DP-1
