# do not change the position of the following lines
# The reason is that those are set by the line number within neovim

cursor #FF3353
foreground #D6F5F9
background #0E2A38

font_family Hurmit
adjust_line_height 0
font_size 12.5

copy_on_select yes

enable_audio_bell no

force_ltr no

mouse_hide_wait 1.0

clipboard_control write-primary write-clipboard no-append
dynamic_background_opacity yes
background_opacity 0.7

dim_opacity 0.0

placement_strategy center
single_window_padding_width 1

map alt+equal set_background_opacity +0.1
map alt+minus set_background_opacity -0.1
map alt+space set_background_opacity 0.1

map ctrl+shift+v paste_from_clipboard
map ctrl+v paste_from_clipboard 
map ctrl+j scroll_line_down
map ctrl+k scroll_line_up

allow_remote_control yes
shell_integration enabled
