background #0E2A38
# position of the following lines
# The reason is that those are set by the line number within neovim
cursor #0fbd35
foreground #d9dbe8
background #23272f

font_family Hasklug Nerd Font
adjust_line_height -1
font_size 13

copy_on_select yes
enable_audio_bell no
tab_separator "󰌥"

modify_font cell_width 95%
modify_font cell_height 95%
modify_font baseline 1

mouse_hide_wait 1.0

clipboard_control write-primary write-clipboard no-append
dynamic_background_opacity yes
background_opacity 0.7

dim_opacity 0.8

placement_strategy center
single_window_padding_width 0
disable_line_wrap yes

map alt+equal set_background_opacity +0.1
map alt+minus set_background_opacity -0.1
map alt+space set_background_opacity 0.1

map ctrl+o new_window
map ctrl+s new_window
map ctrl+h next_window 
map ctrl+l previous_window

map shift+up scroll_page_up
map shift+down scroll_page_up

map ctrl+shift+h move_tab_forward
map ctrl+shift+l move_tab_backward

map ctrl+shift+h move_tab_forward
map ctrl+shift+l move_tab_backward

map ctrl+shift+v paste_from_clipboard
map ctrl+v paste_from_clipboard 
map ctrl+j scroll_line_down
map ctrl+k scroll_line_up

wrap_lines no
map ctrl+l scroll_window_left 5
map ctrl+h scroll_window_right 5 

map ctrl+j scroll_line_down
map ctrl+k scroll_line_up

scrollback_lines 750
enable_layouts horizontal
allow_remote_control yes
shell_integration enabled
