source /etc/environment

./change_conf_util.sh "/home/admin/configs/kitty/kitty.conf" " " "cursor" "$COLOR_foreground"
./change_conf_util.sh "/home/admin/configs/kitty/kitty.conf" " " "foreground" "$COLOR_sub_foreground"
./change_conf_util.sh "/home/admin/configs/kitty/kitty.conf" " " "background" "$COLOR_transparency_background"
./change_conf_util.sh "/home/admin/configs/kitty/kitty.conf" " " "background_opacity" "$THEME_transparency"
./change_conf_util.sh "/home/admin/configs/kitty/kitty.conf" " " "font_size" "$THEME_font_size_m"


./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 1 "window {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 2 "    border-radius: 30px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 3 "    padding: 20px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 4 "    opacity: 0.8;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 5 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 6 "    background-color: #1b1b1b;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 7 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 8 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 9 "#outer-box {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 10 "    margin: 15px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 11 "    border-radius: 20px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 12 "    padding: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 13 "    color: #2b2b2b;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 14 "    background-color: #2b2b2b;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 15 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 16 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 17 "#input {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 18 "    margin: 5px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 19 "    padding: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 20 "    color: #f8fbfc;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 21 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 22 "    border-color: #6818ff;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 23 "    background-color: #3a3a3a;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 24 "    border-radius: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 25 "    border-width: 2px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 26 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 27 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 28 "#inner-box {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 29 "    margin: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 30 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 31 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 32 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 33 "#scroll {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 34 "    margin: 5px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 35 "    border-radius: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 36 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 37 "    border: 1px solid #6818ff;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 38 "    background-color: #3a3a3a;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 39 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 40 "    padding: 1px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 41 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 42 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 43 "#text {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 44 "    opacity: 1;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 45 "    margin: 2px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 46 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 47 "    font-family: cousine nerd font mono;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 48 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 49 "    color: #f0f3f3;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 50 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 51 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 52 ".entry {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 53 "    margin-right: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 54 "    margin-left: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 55 "}"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 56 ""
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 57 "#entry {"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 58 "    margin-right: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 59 "    margin-left: 10px;"
./replace_conf_line.sh "/home/admin/configs/wofi/style.css" 60 "}"
