preload=/home/admin/WallPapers/vert_monitor.png
preload=/home/admin/WallPapers/main_monitor.png

preload=/home/admin/WallPapers/picture_wallpaper.png

wallpaper=HDMI-A-1,/home/admin/WallPapers/vert_monitor.png
wallpaper=DP-1,/home/admin/WallPapers/main_monitor.png
wallpaper=DP-2,/home/admin/WallPapers/main_monitor.png

