binde = SUPER, Equal, exec, pamixer -i 1
binde = SUPER, Minus, exec, pamixer -d 1


bind = SUPERSHIFT, d, submap, center
bind = SUPERSHIFT, d, submap, center
submap = dwindle

binde = SUPER, left,  splitratio, 0.01 -0.01
binde = SUPER, right, splitratio, -0.01 0.01 

bind = SUPER_SHIFT, h, movewindow, l
bind = SUPER_SHIFT, l, movewindow, r
bind = SUPER_SHIFT, k, movewindow, u
bind = SUPER_SHIFT, j, movewindow, d

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

bind = SUPERSHIFT, d, submap, reset
submap = reset
