monitor=HDMI-A-1,2560x1080, -1080x-1080, 1, transform,1
monitor=DP-2, highres, 0x0, 1

source = ~/configs/hyprland/modules/colors.conf


general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 5
    gaps_out = 15
    gaps_workspaces = 15
    border_size = 3
    col.active_border   = $active $active $mid_active $mid_active $highlight $mid_active $mid_active $active $end_active 25deg
    col.inactive_border = $inactive $inactive $inactive $mid_inactive $mid_inactive $inactive $end_inactive $inactive $inactive 20deg

    col.nogroup_border = $end_inactive $end_inactive 20deg
    col.nogroup_border_active = $end_inactive $end_inactive 20deg

    layout = dwindle
    # layout = master
    #layout = hy3
    # layout = scroller

    allow_tearing = false
    resize_on_border = false 
    no_focus_fallback = true 
}

input {
    kb_layout = us,de
    kb_variant =
    kb_model = 
    kb_options = 
    kb_rules =

    natural_scroll = false
    follow_mouse = 2
    repeat_rate = 65 
    repeat_delay = 350

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
    mouse_refocus = true
    off_window_axis_events = 1
    float_switch_override_focus = 0
    special_fallthrough = false 

}


misc {
    vrr = 0
    vfr = true
}


cursor {
    no_hardware_cursors = true
    zoom_factor = 1.0
}

opengl {
    nvidia_anti_flicker = 1
}


xwayland {
    force_zero_scaling = true
}


source = ~/configs/hyprland/keymap/defaults.conf
# source = ~/configs/hyprland/keymap/scroller.conf

# source = ~/configs/hyprland/modules/nvidea_workaurounds.conf
# source = /home/admin/configs/hyprland/keymap/keymap_hy3.conf


