
# Sizing keys
bind = CTRL_R & SUPER, 1,sendshortcut,                 ,F1             ,^(com.obsproject.Studio)$
bind = CTRL_R & SUPER, 2,sendshortcut,                 ,F2             ,^(com.obsproject.Studio)$
bind = CTRL_R & SUPER, 3,sendshortcut,                 ,F3             ,^(com.obsproject.Studio)$
bind = CTRL_R & SUPER, 4,sendshortcut,                 ,F4             ,^(com.obsproject.Studio)$
bind = CTRL_R & SUPER, 5,sendshortcut,                 ,F5             ,^(com.obsproject.Studio)$
bind = CTRL_R & SUPER, 6,sendshortcut,                 ,F6             ,^(com.obsproject.Studio)$
bind = SUPERALT,    Equal,sendshortcut,     SHIFT_CTRL  ,=              ,^(com.obsproject.Studio)$
bind = SUPERALT,    Minus,sendshortcut,     SHIFT_CTRL  ,-              ,^(com.obsproject.Studio)$
bind = SUPERALT,        s,sendshortcut,     CTRL        ,s              ,^(com.obsproject.Studio)$
bind = SUPERALT,        h,sendshortcut,     SHIFT_CTRL  ,s              ,^(com.obsproject.Studio)$

binde = SUPER,  Equal, exec, pamixer -i 1
binde = SUPER,  Minus, exec, pamixer -d 1

bind  = SUPER, O, exec, kitty  --hold sh -c 'neofetch' -o allow_remote_control=yes --listen-on unix:/tmp/mykitty > /dev/null 2>&1
bind  = SUPERSHIFT, S, exec, ~/configs/hyprland/skripts/screenshots.sh


bind  = SUPER,      Z, exec, /home/admin/configs/hyprland/skripts/screenshot_to_drive.sh

bind  = SUPER,      V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind  = SHIFTSUPER, P, exec, hyprpicker -a -f hex  # autocopies color in hex

bind  = SUPER,      E, exec, thunar
bind  = SUPERSHIFT, E, exec, dolphin 

bind  = SUPER,      R, exec, tofi-drun


bind  = SUPER,      N, exec, neovide --vsync -- --listen /home/admin/.cache/nvim/server.pipe
bind  = SUPER,      C, exec, google-chrome-stable --ash-no-nudges
# bind  = SUPER,      s, exec, hyprctl dispatch tagwindow see

bind  = SUPERSHIFT, D, togglefloating
bind  = SUPER,      G, fullscreen
bind  = SUPER,      Q, killactive

bind  = SUPER,      SPACE, togglespecialworkspace, 

bind = SUPER,       U, movetoworkspace, special:-1
bind = SUPER,       D, movetoworkspace, 1

bind  = SUPER,         1, workspace, 1
bind  = SUPER,         2, workspace, 2
bind  = SUPER,         3, workspace, 3
bind  = SUPER,         8, workspace, 4
bind  = SUPER,         9, workspace, 5
bind  = SUPER,         0, workspace, 6

#bind  = SUPERSHIFT,    8, movetoworkspace, 1
bind  = SUPERSHIFT,    1, movetoworkspace, 1
bind  = SUPERSHIFT,    2, movetoworkspacesilent, 2
bind  = SUPERSHIFT,    3, movetoworkspacesilent, 3

bind  = SUPERSHIFT,    8, movetoworkspace, 4
bind  = SUPERSHIFT,    9, movetoworkspacesilent, 5
bind  = SUPERSHIFT,    0, movetoworkspacesilent, 6

bind = SUPER,       M, exec, pypr layout_center toggle # toggle the layout
bind = SUPER, B, exec, pypr expose

bind  = SUPER,        t, tagwindow, no_darken

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow


# bind = ALT,      a, exec,echo "ä" | wl-copy && wtype -M ctrl v -s 200 -m ct 
bind = ALT, A, exec, wtype -P 0x00E4 -s 100 -p 0x00E4 # Ä
# binde = SUPER, 6, exec, echo 'ä' | wl-copy && wl-paste # ö
#bind = SHIFTALT, O, exec, wtype -P \0x00d6 -p \0x00d6 # Ö
#bind = ALT,      u, exec, wtype -P \0x00Fc -p \0x00Fc # ü 
#bind = SHIFTALT, U, exec, wtype -P \0x00dc -p \0x00dc # Ü
#bind = ALT,      s, exec, wtype -P \0x00DF -p \0x00DF # ß

# bind = SUPERALT, 1, exec, hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/start.png"
# bind = SUPERALT, 2, exec, hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/rocket.png"
# bind = SUPERALT, 3, exec, hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/gray_tower.png"
