
# Sizing keys
bind = SUPERALT,        1,sendshortcut,                 ,F1             ,^(com.obsproject.Studio)$
bind = SUPERALT,        2,sendshortcut,                 ,F2             ,^(com.obsproject.Studio)$
bind = SUPERALT,        3,sendshortcut,                 ,F3             ,^(com.obsproject.Studio)$
bind = SUPERALT,    Equal,sendshortcut,     SHIFT_CTRL  ,=              ,^(com.obsproject.Studio)$
bind = SUPERALT,    Minus,sendshortcut,     SHIFT_CTRL  ,-              ,^(com.obsproject.Studio)$
bind = SUPERALT,        s,sendshortcut,     CTRL        ,s              ,^(com.obsproject.Studio)$
bind = SUPERALT,        h,sendshortcut,     SHIFT_CTRL  ,s              ,^(com.obsproject.Studio)$

bind  = SUPERSHIFT, O, exec, kitty --title "Console" -o allow_remote_control=yes --listen-on unix:/tmp/mykitty > /dev/null 2>&1

bind  = SUPERSHIFT, S, exec, ~/configs/hyprland/skripts/screenshots.sh

#bind  = SUPERCTRL, H, changemonitor, +1
#bind  = SUPERCTRL, L, changemonitor, -1 

binde = SUPER,  Equal, exec, pamixer -i 1
binde = SUPER,  Minus, exec, pamixer -d 1

# bind = SUPER, i, invertactivewindow
bind  = SUPER,      V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind  = SUPER,      S, exec, hyprpicker -a -f hex  # autocopies color in hex
bind  = SUPER,      E, exec, thunar
bind  = SUPERSHIFT, E, exec, dolphin 
bind  = SUPER,      R, exec, tofi-drun

bind  = SUPER,      O, exec, nohup kitty -o "linux_display_server=x11" --hold sh -c 'neofetch' -o allow_remote_control=yes --listen-on unix:/tmp/mykitty

bind  = SUPER,      N, exec, env -u WAYLAND_DISPLAY neovide --vsync -- --listen /home/admin/.cache/nvim/server.pipe
bind  = SUPERSHIFT, N, exec, neovide --vsync -- --server 127.0.0.1:6666

bind  = SUPER,      C, exec, google-chrome-stable --in-process-gpu
bind  = SUPERSHIFT, C, exec, google-chrome-stable --in-process-gpu --enable-features=UseOzonePlatform --ozone-platform=wayland

bind  = SUPER,         f, togglefloating
bind  = SUPER,         G, fullscreen
bind  = SUPER,         Q, killactive
bind  = SUPER,     SPACE, togglespecialworkspace, -1

bind  = SUPER,         1, workspace, 1
bind  = SUPER,         2, workspace, 2
bind  = SUPER,         3, workspace, 3

bind  = SUPER,         8, workspace, 4
bind  = SUPER,         9, workspace, 5
bind  = SUPER,         0, workspace, 6

bindse = SUPER_R&SHIFT_L, j, workspace, +1
bindse = SUPER_R&SHIFT_L, k, workspace, -1


bind = SUPER,         U, movetoworkspace,   special:-1
bind = SUPER,         D, movetoworkspace,   1

bind  = SUPERSHIFT,    1, movetoworkspace, 1
bind  = SUPERSHIFT,    2, movetoworkspacesilent, 2
bind  = SUPERSHIFT,    3, movetoworkspacesilent, 3

binds = SHIFT_L & SHIFT_R,    1, movetoworkspacesilent, 1
binds = SHIFT_L & SHIFT_R,    2, movetoworkspacesilent, 2
binds = SHIFT_L & SHIFT_R,    3, movetoworkspacesilent, 3

bind  = SUPERSHIFT,    8, movetoworkspace, 4
bind  = SUPERSHIFT,    9, movetoworkspacesilent, 5
bind  = SUPERSHIFT,    0, movetoworkspacesilent, 6


$one = hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/mandelbrot_green.png"

# bind = ALT,      a, execr, wtype -k \0x00E4
# bind = SHIFTALT, A, exec, wtype -P \0x00c4 -p \0x00c4 # Ä
# bind = ALT,      o, exec, wtype -P \0x00F6 -p \0x00F6 # ö
# bind = SHIFTALT, O, exec, wtype -P \0x00d6 -p \0x00d6 # Ö
# bind = ALT,      u, exec, wtype -P \0x00Fc -p \0x00Fc # ü 
# bind = SHIFTALT, U, exec, wtype -P \0x00dc -p \0x00dc # Ü
# bind = ALT,      s, exec, wtype -P \0x00DF -p \0x00DF # ß

# bind = SUPERALT, 1, exec, hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/start.png"
# bind = SUPERALT, 2, exec, hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/rocket.png"
# bind = SUPERALT, 3, exec, hyprctl hyprpaper wallpaper "DP-1, /home/admin/WallPapers/gray_tower.png"
