
binde = SUPER, left,  splitratio,  0.05 -0.05
binde = SUPER, right, splitratio, -0.05 0.05 

binde = SUPER_L & CTRL_R, h, swapwindow, l
binde = SUPER_L & CTRL_R, l, swapwindow, r

bindse = SUPER_L & SHIFT_R, h, movewindow, l
bindse = SUPER_L & SHIFT_R, l, movewindow, r

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d
