
binde = SUPER, left,  splitratio,  -0.05  0.05
binde = SUPER, right, splitratio,   0.05 -0.05 

bind = SUPERSHIFT, h, movewindow, l
bind = SUPERSHIFT, l, movewindow, r
bind = SUPERSHIFT, k, movewindow, u
bind = SUPERSHIFT, j, movewindow, d

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d
