plugin {
  hy3 {
    # disable gaps when only one window is onscreen
    # 0 - always show gaps
    # 1 - hide gaps with a single window onscreen
    # 2 - 1 but also show the window border
    no_gaps_when_only = 0

    # policy controlling what happens when a node is removed from a group,
    # leaving only a group
    # 0 = remove the nested group
    # 1 = keep the nested group
    # 2 = keep the nested group only if its parent is a tab group
    node_collapse_policy = 0

    # offset from group split direction when only one window is in a group
    group_inset = 10

    # if a tab group will automatically be created for the first window spawned in a workspace
    tab_first_window = false

    # tab group settings
    tabs {
      height = 0
      padding = 5
      from_top = false
      rounding = 3
      render_text = true
      text_center = false
      text_font = sens
      text_height = 8
      text_padding = 3
      col.urgent = 0xffff4f4f
      col.inactive = 0x80808080
      col.text.active = 0xff000000
      col.text.urgent = 0xff000000
      col.text.inactive = 0xff000000
    }

    autotile {
      enable = false
      ephemeral_groups = true
      trigger_width = 0
      trigger_height = 0
      workspaces = all
    }
  }
}

bind = SUPER, b, hy3:changefocus,bottom
bind = SUPER, t, hy3:changefocus,top
bind = SUPER, l, hy3:movefocus,[wrap] right
bind = SUPER, h, hy3:movefocus,[wrap] left

bind = SUPER, [, hy3:makegroup, u 
bind = SUPER, ], hy3:movewindow, l

bind = SUPER, Q, killactive, 
