
# Move focus with mainMod + arrow keys
bind = SUPER,      k,       scroller:movefocus, u
bind = SUPER,      j,       scroller:movefocus, d
bind = SUPER,      f,       scroller:fitsize, active
binde = SUPER,     l,       scroller:movefocus, r 
binde = SUPER,     h,       scroller:movefocus, l

bind = SUPER,      up,      scroller:cyclesize, next
bind = SUPER,      down,    scroller:cyclesize, prev

binde = SUPER,     right,   resizeactive, 10 0
binde = SUPER,     left,    resizeactive, -10 0

bind = SUPER,      t,       scroller:admitwindow,
bind = SUPER,      w,       scroller:expelwindow,

# Sizing keys
bind = SUPERSHIFT, l, scroller:movewindow, r
bind = SUPERSHIFT, h, scroller:movewindow, l
bind = SUPERSHIFT, j, scroller:movewindow, d
bind = SUPERSHIFT, k, scroller:movewindow, u

bind = SUPER, bracketright, scroller:expelwindow,
bind = SUPER, bracketleft, scroller:admitwindow,

bind=  SUPER,      c, submap,        centered

bind = SUPER,      Q, killactive, 

bind = SUPER,      SPACE, togglespecialworkspace,
bind = SUPER,      U,     movetoworkspace, special
bind = SUPER,      D,     movetoworkspace, 2

bind = SUPER,      v,     exec, hyprctl dispatch focusmonitor HDMI-A-1
bind = SUPER,      m,     exec, hyprctl dispatch focusmonitor DP-1
bind = SUPERSHIFT, v,     movetoworkspace, 1
bind = SUPERSHIFT, m,     movetoworkspace, 2

bind = SUPER, O, exec, nohup kitty --hold sh -c 'neofetch' -o allow_remote_control=yes --listen-on unix:/tmp/mykitty
bind = SUPER, N, exec, neovide -- --listen /tmp/myNvim && sleep 0.1 && hyprctl dispatch fullscreen && hyprctl dispatch fullscreen

submap=centered
    bind = SUPER, l, scroller:movefocus, r 
    bind = SUPER, h, scroller:movefocus, l

    bind = SUPER, l, scroller:alignwindow, c
    bind = SUPER, h, scroller:alignwindow, c

    bind = SUPER, l, exec, hyprctl dispatch forcerenderreload
    bind = SUPER, h, exec, hyprctl dispatch forcerenderreload

    bind = SUPER, SPACE, togglespecialworkspace, 2

    bind = SUPER, c,     submap,                 reset
submap=reset
