master {
    new_is_master = true
    inherit_fullscreen = false
    allow_small_split = true
}

binde = SUPER, left,  splitratio, 0.01 -0.01
binde = SUPER, right, splitratio, -0.01 0.01 

bind = SUPERSHIFT, h, movewindow, l
bind = SUPERSHIFT, l, movewindow, r
bind = SUPERSHIFT, k, movewindow, u
bind = SUPERSHIFT, j, movewindow, d

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
