plugin{
    scroller {
        focus_wrap = true
        column_widths = onefourth onehalf threequarters one
        window_heights = onethird onehalf one

        monitor_options = (
            DP-1 = (mode = row; column_default_width = onehalf; window_default_height = one),
            HDMI-A-1 = (mode = row; column_default_width = twothirds; window_default_height = one; column_widths = onethird twothirds one))
        jump_labels_scale=0.5
        jump_labels_keys=aoeuisnthd

        # monitor_options = (DP-1 = (mode = row; column_default_width = onehalf; window_default_height = one), HDMI-A-1 = (mode = row; column_default_width = onethird; window_default_height = one))
    }
}


# Move focus with mainMod + arrow keys



binds = SHIFT_R & SHIFT_L,   h, scroller:movefocus, l
binds = SHIFT_R & SHIFT_L,   l, scroller:movefocus, r

binds = SHIFT_R & SHIFT_L,   k, scroller:movefocus, u
binds = SHIFT_R & SHIFT_L,   j, scroller:movefocus, d

bind = SUPER,      m,       scroller:pin


# Sizing keys
bind = SUPERSHIFT, l, scroller:movewindow, r
bind = SUPERSHIFT, h, scroller:movewindow, l

# bind = SUPERSHIFT, j, scroller:movewindow, d
# bind = SUPERSHIFT, k, scroller:movewindow, u

bind = SUPERCTRL, l, scroller:movefocus, r
bind = SUPERCTRL, l, scroller:expelwindow
bind = SUPERCTRL, l, scroller:movefocus, u

bind = SUPERCTRL, h, scroller:admitwindow
bind = SUPERCTRL, h, scroller:movewindow, l
bind = SUPERCTRL, h, scroller:expelwindow, l

bind = SUPER, bracketright, scroller:expelwindow,
bind = SUPER, bracketleft,  scroller:admitwindow,

bind = SUPERSHIFT, bracketright, scroller:fitsize, toend
bind = SUPERSHIFT, bracketleft,  scroller:fitsize, tobeg

