plugin{
    scroller {
        focus_wrap = true
        column_widths = onesixth onefourth onehalf threequarters fivesixths one
        window_heights = onefourth onehalf threequarters one
        monitor_options = (DP-1 = (mode = row; column_default_width = onehalf; window_default_height = one), HDMI-A-1 = (mode = col; column_default_width = one; window_default_height = onehalf))
        # monitor_options = (DP-1 = (mode = row; column_default_width = onehalf; window_default_height = one), HDMI-A-1 = (mode = row; column_default_width = onethird; window_default_height = one))
    }
}


# Move focus with mainMod + arrow keys
bind = SUPER,      h,       scroller:movefocus, l
bind = SUPER,      l,       scroller:movefocus, r


bind = SUPER,      k,       scroller:movefocus, u
bind = SUPER,      j,       scroller:movefocus, d

bind = SUPER,      v,       scroller:fitsize, active
bind = SUPER,      a,       scroller:alignwindow, center

bind = SUPER,      f,       scroller:fitsize, visible
bind = SUPER,      t,       scroller:toggleoverview,

binds = SHIFT_R & SHIFT_L,   h, scroller:movefocus, l
binds = SHIFT_R & SHIFT_L,   l, scroller:movefocus, r

bind = SUPER,      m,       scroller:pin
bind = SUPERSHIFT, m,       scroller:unpin


bind = SUPER,      up,      scroller:cyclesize, next
bind = SUPER,      down,    scroller:cyclesize, prev

bind = SUPER,      left,    scroller:cyclesize, next
bind = SUPER,      left,    scroller:cyclesize, next

bind = SUPER,      right,   scroller:cyclesize, prev
bind = SUPER,      right,   scroller:cyclesize, prev


# Sizing keys
bind = SUPERSHIFT, l, scroller:movewindow, r
bind = SUPERSHIFT, h, scroller:movewindow, l

bind = SUPERSHIFT, j, scroller:movewindow, d
bind = SUPERSHIFT, k, scroller:movewindow, u

bind = SUPERCTRL, l, scroller:movefocus, r
bind = SUPERCTRL, l, scroller:expelwindow
bind = SUPERCTRL, l, scroller:movefocus, u

bind = SUPERCTRL, h, scroller:admitwindow
bind = SUPERCTRL, h, scroller:movewindow, l
bind = SUPERCTRL, h, scroller:expelwindow, l

bind = SUPER, bracketright, scroller:expelwindow,
bind = SUPER, bracketleft,  scroller:admitwindow,

bind = SUPERSHIFT, bracketright, scroller:fitsize, toend
bind = SUPERSHIFT, bracketleft,  scroller:fitsize, tobeg
