
# Move focus with mainMod + arrow keys
bind = SUPER,      k,       scroller:movefocus, u
bind = SUPER,      j,       scroller:movefocus, d
bind = SUPER,      f,       scroller:fitsize, active

bind = SUPER,      h,       scroller:movefocus, l
bind = SUPER,      l,       scroller:movefocus, r

bind = SUPER,      up,      scroller:cyclesize, next
bind = SUPER,      down,    scroller:cyclesize, prev

binde = SUPER,     right,   resizeactive, 10 0
binde = SUPER,     left,    resizeactive, -10 0

bind = SUPER,      t,       scroller:admitwindow,
bind = SUPER,      w,       scroller:expelwindow,

# Sizing keys
bind = SUPERSHIFT, l, scroller:movewindow, r
bind = SUPERSHIFT, h, scroller:movewindow, l

bind = SUPERSHIFT, j, scroller:movewindow, d
bind = SUPERSHIFT, k, scroller:movewindow, u

bind = SUPER, bracketright, scroller:expelwindow,
bind = SUPER, bracketleft,  scroller:admitwindow,

bind = SUPERALT,   h, scroller:alignwindow, l
bind = SUPERALT,   l, scroller:alignwindow, r

bind = SUPER,      up, exec, hyprctl dispatch forcerenderreload
bind = SUPER,      down, exec, hyprctl dispatch forcerenderreload
bind = SUPER,      j, exec, sleep 1 & hyprctl dispatch forcerenderreload
bind = SUPER,      k, exec, sleep 1 & hyprctl dispatch forcerenderreload

bind = SUPER,      v,     exec, hyprctl dispatch focusmonitor HDMI-A-1
bind = SUPERSHIFT, V,     movetoworkspace, vert
bind = SUPER,      m,     exec, hyprctl dispatch focusmonitor DP-1
bind = SUPERSHIFT, M,     movetoworkspace, main

bind = SUPER,      U,     movetoworkspace, special:main
bind = SUPER,      D,     movetoworkspace, name:main


submap=centered
    bind = SUPER, l, scroller:movefocus, r 
    bind = SUPER, h, scroller:movefocus, l

    bind = SUPER, l, scroller:alignwindow, c
    bind = SUPER, h, scroller:alignwindow, c

    bind = SUPER, l, exec, hyprctl dispatch forcerenderreload
    bind = SUPER, h, exec, hyprctl dispatch forcerenderreload

    bind = SUPER, SPACE, togglespecialworkspace, 2

    bind = SUPER, c,     submap,                 reset
submap=reset
