bind  = SUPER,         1,   split-workspace, 1
bind  = SUPER,         2,   split-workspace, 2

bind = SUPERSHIFT,     1, split-movetoworkspace, 1
bind = SUPERSHIFT,     2, split-movetoworkspace, 2

bind = SUPER,          u, split-movetoworkspace, special:-1
bind = SUPER,          d, split-movetoworkspace, name:1

bind = SUPERSHIFT,     u, split-movetoworkspace, special:-2
bind = SUPERSHIFT,     d, split-movetoworkspace, name:2
