
plugin {
    virtual-desktops {
        names = 1:code, 2:internet, 3:other
        cycleworkspaces = 3
        rememberlayout = size
        notifyinit = 1
        verbose_logging = 0
    }
}


bind = SUPER, 1, vdesk, code
bind = SUPER, 2, vdesk, internet
bind = SUPER, 3, vdesk, other

bind = SUPER, 8, movetodesk, code
bind = SUPER, 9, movetodesk, internet
bind = SUPER, 0, movetodesk, other

bind = SUPERSHIFT, Plus, vdesk, cyclevdesks
bind = SUPERSHIFT, Minus, vdesk, backcyclevdesks
