
plugin {
    virtual-desktops {
        names = 1:code, 2:internet, 3:other
        cycleworkspaces = 3
        rememberlayout = size, monitors
        notifyinit = 1
        verbose_logging = 0
    }
}


bind  = SUPERSHIFT, -, exec, lastdesk 
bind  = SUPERSHIFT, +, exec, nextdesk

bind = SUPER, 1, vdesk, code
bind = SUPER, 2, vdesk, internet
bind = SUPER, 3, exec, vdesk other
